### ISSUE TITLE
Thank you for your effertness, and some questions.

### ISSUE THREAD

**Issue by dgjung0220** [Li-Chongyi/UHDFour_code#3]
In this paper, there is a question as follows:
In the current model, the shapes of the amplitude and phase components do not appear as in the image. I am curious about the adjustments made for the visualization of the images in the paper.

**Comment by Li-Chongyi** [comment]
Hi,

There are several ways to visualize the amplitude and phase. you may need
to try. But I do not save that code to visualize them.

Best regards,


DONGGOO JUNG ***@***.***> 于2023年11月27日周一 15:36写道：
